name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test
    - name: Build images
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/auth-service:${{ github.sha }} ./services/auth
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/auth-service:${{ github.sha }}
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/trips-service:${{ github.sha }} ./services/trips
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/trips-service:${{ github.sha }}
    - name: Deploy to GKE
      uses: google-github-actions/deploy-gke@v0
      with:
        cluster: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_REGION }}
        manifest: k8s/
      env:
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
